FROM python:3.9-slim

WORKDIR /app

COPY requirements.collector.txt /tmp/requirements.collector.txt
RUN pip install --no-cache-dir -r /tmp/requirements.collector.txt

CMD ["python", "/app/producer.py"]