FROM apache/airflow:2.7.1

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.airflow.txt /tmp/requirements.airflow.txt

USER airflow
RUN pip install --no-cache-dir -r /tmp/requirements.airflow.txt